apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
      tier: backend
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      volumes:
        - name: php-data
          hostPath:
            path: /home/shoaib/php-container 
      containers:
      - name: php
        image: bitnami/php-fpm
        ports:
            - containerPort: 9000
        volumeMounts:
        - name: php-data
          mountPath: /var/www/html
