apiVersion: v1
kind: Service
metadata:
  name: app-db
  labels:
    tier: backend
spec:
  selector:
    app: app-db
    tier: backend
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP
